amqp:
  url: amqp://localhost:5672/
  grading_queue: cs225-grade
  started_queue: cs225-started
  result_queue: cs225-result
grader_repo:
  repo_url: git@github.com:kevinwang/pl-cs225-grader.git
  commit: origin/master
  credentials:
    public_key: /opt/autograd/_ssh/ssh-publickey
    private_key: /opt/autograd/_ssh/ssh-privatekey
    passphrase:
