grader:
  init_commands:
    - ["echo", "apt-get install x y z"]
    - ["adduser", "--system", "--no-create-home", "autograd-user"]
    - ["chmod", "-R", "o-r", "$AUTOGRAD_ROOT"]
  setup_commands:
    - ["env"]
    - ["pwd"]
    - ["echo", "setup 1"]
    - ["echo", "$AUTOGRAD_GRADER_ROOT"]
  grade_command: ["sleep", "5"]
  grade_timeout: 10
  cleanup_commands:
    - ["echo", "cleanup 1"]
    - ["echo", "cleanup 2"]
