apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autograd-cs225
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: autograd-cs225
    spec:
      containers:
        - name: autograd-cs225
          image: prairielearn/autograd
          volumeMounts:
            - name: config-volume
              mountPath: /opt/autograd/_conf
            - name: ssh-keys
              mountPath: /opt/autograd/_ssh
      volumes:
        - name: config-volume
          configMap:
            name: autograd-cs225-config
            items:
              - key: configuration.yml
                path: configuration.yml
        - name: ssh-keys
          secret:
            secretName: autograd-ssh-keys
