apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autograd
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: autograd
    spec:
      containers:
        - name: autograd
          image: prairielearn/autograd
          volumeMounts:
            - name: config-volume
              mountPath: /opt/autograd/_conf
            - name: ssh-keys
              mountPath: /opt/autograd/_ssh
      volumes:
        - name: config-volume
          configMap:
            name: autograd-cs225-config
            items:
              - key: configuration.yml
                path: configuration.yml
        - name: ssh-keys
          secret:
            secretName: autograd-ssh-keys
            items:
              - key: ssh-publickey
                path: id_rsa.pub
              - key: ssh-privatekey
                path: id_rsa
